require('dotenv').config();

const fs = require('fs');
const os = require('os');
const path = require('path');
const anchor = require('@coral-xyz/anchor');
const { Connection, PublicKey, Keypair, clusterApiUrl } = require('@solana/web3.js');

function envOrDefault(name, fallback) {
  return process.env[name] && process.env[name].trim() !== ''
    ? process.env[name].trim()
    : fallback;
}

function loadKeypair(filePath) {
  const resolved = filePath
    ? filePath.replace(/^~\//, os.homedir() + '/')
    : path.join(os.homedir(), '.config', 'solana', 'id.json');
  const secret = JSON.parse(fs.readFileSync(resolved, 'utf8'));
  return Keypair.fromSecretKey(Uint8Array.from(secret));
}

async function main() {
  const RPC_URL = envOrDefault('RPC_URL', clusterApiUrl('devnet'));
  const PAYER_KEYPAIR = process.env.PAYER_KEYPAIR;
  const payer = loadKeypair(PAYER_KEYPAIR);

  const programIdStr = envOrDefault('COMPLIANCE_PROGRAM_ID', '');
  if (!programIdStr) throw new Error('Set COMPLIANCE_PROGRAM_ID in .env');
  const programId = new PublicKey(programIdStr);

  const membersCsv = envOrDefault('GOVERNANCE_MEMBERS', '');
  if (!membersCsv) throw new Error('Set GOVERNANCE_MEMBERS (comma-separated pubkeys) in .env');
  const members = membersCsv.split(',').map((s) => new PublicKey(s.trim()));

  const threshold = parseInt(envOrDefault('GOVERNANCE_THRESHOLD', '3'), 10);
  if (!Number.isInteger(threshold) || threshold <= 0) throw new Error('GOVERNANCE_THRESHOLD must be a positive integer');

  const delaySeconds = parseInt(envOrDefault('GOVERNANCE_DELAY_SECONDS', '86400'), 10);
  if (!Number.isInteger(delaySeconds) || delaySeconds < 0) throw new Error('GOVERNANCE_DELAY_SECONDS must be a non-negative integer');

  const connection = new Connection(RPC_URL, 'confirmed');
  const wallet = new anchor.Wallet(payer);
  const provider = new anchor.AnchorProvider(connection, wallet, {});
  anchor.setProvider(provider);

  // Load IDL generated by `anchor build`
  const idlPath = path.join(process.cwd(), 'target', 'idl', 'compliance_wrapper.json');
  if (!fs.existsSync(idlPath)) {
    throw new Error('IDL not found at ' + idlPath + ' — run `anchor build` first.');
  }
  const idl = JSON.parse(fs.readFileSync(idlPath, 'utf8'));

  const program = new anchor.Program(idl, programId, provider);

  const [governancePda] = PublicKey.findProgramAddressSync(
    [Buffer.from('governance')],
    program.programId
  );

  console.log('RPC:', RPC_URL);
  console.log('Program:', program.programId.toBase58());
  console.log('Payer:', payer.publicKey.toBase58());
  console.log('Governance PDA:', governancePda.toBase58());
  console.log('Members:', members.map((m) => m.toBase58()));
  console.log('Threshold:', threshold);
  console.log('Delay (s):', delaySeconds);

  const txSig = await program.methods
    .initializeGovernance(members, threshold, new anchor.BN(delaySeconds))
    .accounts({
      payer: payer.publicKey,
      governance: governancePda,
      systemProgram: anchor.web3.SystemProgram.programId,
    })
    .signers([payer])
    .rpc();

  console.log('initialize_governance tx:', txSig);
}

main().catch((err) => {
  console.error('Error:', err.message || err);
  process.exit(1);
});
